import type { BenchmarkRun } from "./history";

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadJSON(data: unknown, filename: string) {
  downloadFile(JSON.stringify(data, null, 2), filename, "application/json");
}

export function downloadText(text: string, filename: string) {
  downloadFile(text, filename, "text/plain");
}

export function formatFullReport(run: BenchmarkRun): string {
  const date = new Date(run.timestamp).toLocaleString();
  const line = "─".repeat(48);

  const likelyModels = run.top_fits.filter((f) =>
    run.all_fits ? run.all_fits.some((af) => `${af.model} ${af.quant}` === f && af.fit === "likely") : true
  );

  const maybeModels = run.all_fits
    ? run.all_fits.filter((f) => f.fit === "maybe").map((f) => `${f.model} ${f.quant} (${f.ram_gb}GB)`)
    : [];

  let report = `LLMETER BENCHMARK REPORT
${line}
Date         : ${date}
Score        : ${run.final_score} / 100
Tier         : ${run.tier}
${line}

DEVICE INFO
${line}
RAM          : ${run.ram_gb} GB${run.device_info?.ram_source === "manual" ? " (user-selected)" : " (browser estimate)"}
CPU Cores    : ${run.cores}
Architecture : ${run.arch}
OS           : ${run.device_info?.os ?? "Unknown"}
GPU          : ${run.gpu_renderer || "Unknown"}
GPU Vendor   : ${run.device_info?.gpu_vendor ?? "Unknown"}
WebGPU       : ${run.device_info?.webgpu_available ? "Available" : "Not available"}
WebGL2       : ${run.device_info?.webgl2_available ? "Available" : "Not available"}
WASM SIMD    : ${run.device_info?.simd_supported ? "Supported" : "Not supported"}
Threads      : ${run.device_info?.threads_supported ? "Supported" : "Not supported"}
Unified Mem  : ${run.device_info?.unified_memory ? "Yes (Apple Silicon)" : "No"}
Screen       : ${run.device_info ? `${run.device_info.screen_width}×${run.device_info.screen_height} @${run.device_info.device_pixel_ratio}x` : "Unknown"}
${line}

BENCHMARK RESULTS
${line}
Perf Factor  : ${run.perf_raw ? run.perf_raw.real_perf_factor.toFixed(4) : run.perf_factor?.toFixed(4) ?? "N/A"}x
CPU Ops/sec  : ${run.perf_raw ? (run.perf_raw.cpu.ops_per_sec / 1000).toFixed(1) + "k" : "N/A"}
Memory BW    : ${run.perf_raw ? run.perf_raw.memory.bandwidth_gb_s.toFixed(2) + " GB/s" : "N/A"}
IDB Write    : ${run.perf_raw ? run.perf_raw.storage.write_mb_s.toFixed(0) + " MB/s" : "N/A"} (IPC overhead, not raw SSD)
IDB Read     : ${run.perf_raw ? run.perf_raw.storage.read_mb_s.toFixed(0) + " MB/s" : "N/A"} (IPC overhead, not raw SSD)
CPU Factor   : ${run.perf_raw ? run.perf_raw.cpu_factor.toFixed(3) : "N/A"}
Mem Factor   : ${run.perf_raw ? run.perf_raw.mem_factor.toFixed(3) : "N/A"}
Disk Factor  : ${run.perf_raw ? run.perf_raw.disk_factor.toFixed(3) : "N/A"}
${line}

SCORE BREAKDOWN
${line}
RAM Score    : ${run.score_breakdown?.ram_pts ?? "N/A"} / 40
CPU Score    : ${run.score_breakdown?.cpu_pts ?? "N/A"} / 20
Arch Score   : ${run.score_breakdown?.arch_pts ?? "N/A"} / 15
Accel Score  : ${run.score_breakdown?.accel_pts ?? "N/A"} / 15
GPU Score    : ${run.score_breakdown?.gpu_pts ?? "N/A"} / 10
Base Score   : ${run.score_breakdown?.base_score ?? "N/A"} / 100
Final Score  : ${run.final_score} (base × ${run.perf_factor?.toFixed(3) ?? "perf factor"})
${line}

TOKEN SPEED ESTIMATE
${line}
Estimated    : ${run.tps_low}–${run.tps_high} tokens/sec
Path         : ${run.tps_info?.path ?? "CPU"}
Bottleneck   : ${run.tps_info?.limiting_factor ?? "N/A"}
Context      : 4096 tokens
${line}

MODELS LIKELY TO RUN
${line}
${run.top_fits.length > 0 ? run.top_fits.map((f) => `✓  ${f}`).join("\n") : "None — run a benchmark to populate this"}
${line}

${maybeModels.length > 0 ? `MODELS THAT MIGHT WORK (MARGINAL RAM)
${line}
${maybeModels.map((m) => `~  ${m}`).join("\n")}
${line}

` : ""}Generated by LLMeter — browser-side LLM compatibility benchmark
All results are estimates. Actual performance depends on runtime environment.
`;

  return report;
}

export function copyToClipboard(text: string): Promise<void> {
  if (navigator.clipboard) {
    return navigator.clipboard.writeText(text);
  }
  const el = document.createElement("textarea");
  el.value = text;
  document.body.appendChild(el);
  el.select();
  document.execCommand("copy");
  document.body.removeChild(el);
  return Promise.resolve();
}
